version: "3.8"

services:
  drivernos:
    image: jackson147/drivernos:0.2
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "12"
    environment:
      - TOKEN=deadbeef-a7c6-46d9-8d10-deadbeef
    volumes:
      - ./secrets/:/drivernos/secrets:rw
      - /home/morphos/data:/run/app/data:rw
